openapi: 3.0.0
info:
  title: Converted from company.models.swagger.yaml with typeconv
  version: "1"
paths: {}
components:
  schemas:
    Roles:
      type: string
      enum:
        - Admin
        - Volunteer
        - Student
        - Teacher
        - Parent
    CreateUser:
      title: CreateUser
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          $ref: "#/components/schemas/Roles"
      required:
        - id
        - firstName
        - lastName
        - email
        - role
      additionalProperties: false
    UpdateUser:
      title: User
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          $ref: "#/components/schemas/Roles"
        pictureId:
          type: string
        approved:
          type: boolean
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          $ref: "#/components/schemas/Roles"
        pictureId:
          type: string
        approved:
          type: boolean
        dateCreated:
          type: string
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
      required:
        - id
        - firstName
        - lastName
        - email
        - role
        - pictureId
        - approved
        - dateCreated
        - phoneNumber
        - address
      additionalProperties: false
    Student:
      title: Student
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          $ref: "#/components/schemas/Roles"
        pictureId:
          type: string
        approved:
          type: boolean
        dateCreated:
          type: string
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        level:
          type: number
          nullable: true
        classes:
          type: array
          items:
            type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - role
        - pictureId
        - approved
        - dateCreated
        - phoneNumber
        - address
        - level
        - classes
    Staff:
      title: Staff
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          $ref: "#/components/schemas/Roles"
        pictureId:
          type: string
        approved:
          type: boolean
        dateCreated:
          type: string
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        minLevel:
          type: number
          nullable: true
        maxLevel:
          type: number
          nullable: true
        language:
          type: string
          nullable: true
      required:
        - id
        - firstName
        - lastName
        - email
        - role
        - pictureId
        - approved
        - dateCreated
        - phoneNumber
        - address
        - minLevel
        - maxLevel
        - language
    UpdateModule:
      title: UpdateModule
      type: object
      properties:
        name:
          type: string
        position:
          type: number
    CreateModule:
      title: CreateModule
      type: object
      properties:
        name:
          type: string
        position:
          type: number
        classId:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - role
        - pictureId
        - approved
        - dateCreated
        - phoneNumber
        - address
        - classId
        - name
        - position
    Module:
      title: Module
      type: object
      properties:
        moduleId:
          type: string
        name:
          type: string
        position:
          type: number
        classId:
          type: string
      required:
        - name
        - position
        - classId
        - moduleId
    CreateItem:
      title: CreateItem
      type: object
      properties:
        title:
          type: string
        link:
          type: string
      required:
        - title
        - link
    Item:
      title: Item
      type: object
      properties:
        title:
          type: string
        link:
          type: string
        moduleId:
          type: string
        itemId:
          type: string
      required:
        - title
        - link
        - moduleId
        - itemId
    UpdateImage:
      title: UpdateImage
      type: object
      properties:
        img:
          type: string
        mimeType:
          type: string
      required:
        - img
        - mimeType
    Image:
      title: Image
      type: object
      properties:
        img:
          type: string
          nullable: true
        mimeType:
          type: string
          nullable: true
        id:
          type: string
      required:
        - id
        - img
        - mimeType
    ClassEvent:
      title: ClassEvent
      type: object
      properties:
        eventInformationId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        timeZone:
          type: string
        rrule:
          type: string
        language:
          type: string
        neverEnding:
          type: boolean
        backgroundColor:
          type: string
      required:
        - eventInformationId
        - startTime
        - endTime
        - timeZone
        - rrule
        - language
        - neverEnding
        - backgroundColor
    CreateClassEvent:
      title: CreateClassEvent
      type: object
      properties:
        startTime:
          type: string
        endTime:
          type: string
        timeZone:
          type: string
        rrule:
          type: string
        language:
          type: string
        neverEnding:
          type: boolean
        backgroundColor:
          type: string
        name:
          type: string
        teachers:
          type: array
          items:
            type: string
        studentIds:
          type: array
          items:
            type: string
        volunteerIds:
          type: array
          items:
            type: string
        checkAvailabilities:
          type: boolean
      required:
        - startTime
        - endTime
        - timeZone
        - rrule
        - language
        - neverEnding
        - backgroundColor
        - teachers
        - studentIds
        - volunteerIds
        - checkAvailabilities
        - name
    UpdateClass:
      title: UpdateClass
      type: object
      properties:
        minLevel:
          type: number
        maxLevel:
          type: number
        rrstring:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        language:
          type: string
    CreateClass:
      title: CreateClass
      type: object
      properties:
        minLevel:
          type: number
        maxLevel:
          type: number
        rrstring:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        language:
          type: string
        eventInformationId:
          type: string
      required:
        - eventInformationId
        - minLevel
        - maxLevel
        - rrstring
        - startTime
        - endTime
        - language
    Class:
      title: Class
      type: object
      properties:
        minLevel:
          type: number
        maxLevel:
          type: number
        rrstring:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        language:
          type: string
        eventInformationId:
          type: string
        name:
          type: string
        teachers:
          type: array
          items:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              userId:
                type: string
            required:
              - firstName
              - lastName
              - userId
      required:
        - eventInformationId
        - minLevel
        - maxLevel
        - rrstring
        - startTime
        - endTime
        - language
        - name
        - teachers
    Availability:
      title: Availability
      type: object
      properties:
        mon:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        tue:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        wed:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        thu:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        fri:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        sat:
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        timeZone:
          type: string
      required:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - timeZone
    AttendanceTypes:
      type: string
      enum:
        - Unexcused
        - Excused
        - Present
      nullable: true
    Attendance:
      title: AttendanceComponent
      type: object
      properties:
        sessionId:
          type: string
        userId:
          type: string
        attendance:
          $ref: "#/components/schemas/AttendanceTypes"
        firstName:
          type: string
        lastName:
          type: string
      required:
        - sessionId
        - userId
        - attendance
        - firstName
        - lastName
    CreateAttendance:
      title: CreateAttendance
      type: object
      properties:
        userId:
          type: string
        attendance:
          $ref: "#/components/schemas/AttendanceTypes"
      required:
        - userId
        - attendance
    SingleUserAttendance:
      title: SingleUserAttendance
      type: object
      properties:
        sessionId:
          type: string
        userId:
          type: string
        attendance:
          $ref: "#/components/schemas/AttendanceTypes"
        start:
          type: string
      required:
        - sessionId
        - userId
        - attendance
        - start
    Announcement:
      title: Announcement
      type: object
      properties:
        eventInformationId:
          type: string
        title:
          type: string
        content:
          type: string
        announcementId:
          type: string
      required:
        - announcementId
        - eventInformationId
        - title
        - content
    CreateAnnouncement:
      title: CreateAnnouncement
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
    CalendarEvent:
      title: CalendarEvent
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        backgroundColor:
          type: string
        start:
          type: string
        end:
          type: string
      required:
        - id
        - title
        - backgroundColor
        - start
        - end
    OneOffEvent:
      title: OneOffEvent
      type: object
      properties:
        eventInformationId:
          type: string
        name:
          type: string
        color:
          type: string
        start:
          type: string
        end:
          type: string
      required:
        - name
        - color
        - start
        - end
    CreateOneOffEvent:
      title: CreateOneOffEvent
      type: object
      properties:
        name:
          type: string
        color:
          type: string
        start:
          type: string
        end:
          type: string
        attendees:
          type: array
          items:
            type: object
            properties:
              role:
                type: string
              userId:
                type: string
            required:
              - role
              - userId
        checkAvailabilities:
          type: boolean
      required:
        - eventInformationId
        - name
        - color
        - start
        - end
        - attendees
        - checkAvailabilities
    CreateParentStudentLink:
      title: CreateParentStudentLink
      type: object
      properties:
        email:
          type: string
      required:
        - email
    ParentStudentLink:
      title: ParentStudentLink
      type: object
      properties:
        parentId:
          type: string
        studentId:
          type: string
      required:
        - parentId
        - studentId
    SessionInformation:
      title: SessionInformation
      type: object
      properties:
        sessionId:
          type: string
        startStr:
          type: string
        endStr:
          type: string
      required:
        - sessionId
        - startStr
        - endStr
    MissingAttendance:
      title: MissingAttendance
      type: object
      properties:
        eventInformationId:
          type: string
        startStr:
          type: string
      required:
        - sessionId
        - startStr
    UpdateEvent:
      title: UpdateEvent
      type: object
      properties:
        name:
          type: string
