name: ci

on:
  pull_request:
    branches: [master]
jobs:
  web:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Migrations
        run: node scripts/migrate.ts
        env:
          DB_USER: "postgres"
          DB_HOST: "localhost"
          DB_PASS: "postgres"
      - name: Test Unit Tests
        run: npm run test
        env:
          DB_USER: "postgres"
          DB_HOST: "localhost"
          DB_PASS: "postgres"
          TYPE: "service_account"
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL}}
          CLIENT_x509_CERT_URL: ${{ secrets.CLIENT_x509_CERT_URL }}
          NO_AUTH: "true"
      - name: Lint
        run: npm run lint-check
      - name: Build
        run: npm run build
