name: ci

on:
  pull_request:
    branches: [master]
jobs:
  web:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Migrations
        run: node scripts/migrate.ts
        env:
          DB_USER: "postgres"
          DB_HOST: "localhost"
          DB_PASS: "postgres"
      - name: Test Unit Tests
        run: npm run test
        env:
          DB_USER: "postgres"
          DB_HOST: "localhost"
          DB_PASS: "postgres"
      - name: Lint
        run: npm run lint-check
